# Copyright (c) 2026, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

application:
  tenants:
    AppProvider:
      users:
        - app-provider
    Seller:
      users:
        - seller
    Buyer:
      users:
        - buyer
    Logistics:
      users:
        - logistics
    Finance:
      users:
        - finance

security.token: "${APP_PROVIDER_BACKEND_USER_TOKEN}"

